GNS-Science/nzshm-opensha

src/main/java/nz/cri/gns/NZSHM22/opensha/hazard/NZSHM22_HazardCalculatorBuilder.java
=> [#21] set PGA/SA period

src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_SubductionInversionConfiguration.java
We started using water levels in some of our subduiction report tests, this just keeps it working without any upstream changes.
=> water level demo works in FullPipelineDemo (again)

src/main/java/nz/cri/gns/NZSHM22/util/NZSHM22_ReportPageGen.java
might as well get this out while we wait for polygons
=> ReportPageGen: finer control over the plots included

.gitignore, src/integration/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_InversionRunner_IntegrationTest.java, src/main/java/nz/cri/gns/NZSHM22/opensha/enumTreeBranches/NZSHM22_LogicTreeBranch.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_AbstractInversionRunner.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionRunner.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_InversionFaultSystemRuptSet.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_SubductionInversionRunner.java, src/main/java/nz/cri/gns/NZSHM22/opensha/scripts/FullPipelineCrustal.java, src/main/java/nz/cri/gns/NZSHM22/opensha/scripts/FullPipelineDemo.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_InversionFaultSystemRuptSetTest.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_InversionFaultSystemSolutionTest.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_SubductionInversionTargetMFDsTest.java
closes the NZ part of #57 
as discussed, a refactor is probably required to do the opensha part
=> [#57] recalc mags

src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionConfiguration.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionRunner.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionTargetMFDs.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionTargetMFDsTest.java
Might as well since we're happy-ish with the targetMFDs again
=> [#30] configurable minMag

.github/workflows/gradle.yml, README.md, src/main/java/nz/cri/gns/NZSHM22/opensha/util/NZSHM22_PythonGateway.java, src/main/java/nz/cri/gns/NZSHM22/util/GitVersion.java, src/main/resources/opensha-ref.txt, src/main/resources/tagged-version.txt
=> [#71] github jar builds

src/main/java/nz/cri/gns/NZSHM22/opensha/enumTreeBranches/NZSHM22_ScalingRelationshipNode.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_AbstractInversionRunner.java
=> [#107] fix scaling config check

src/main/java/nz/cri/gns/NZSHM22/opensha/enumTreeBranches/NZSHM22_FaultModels.java, src/main/resources/faultModels/cfm_0_9b_d90_all.xml, src/main/resources/faultModels/cfm_0_9b_d90_all_stirling_depths.xml, src/main/resources/faultModels/cfm_0_9b_d90_no_tvz.xml, src/main/resources/faultModels/cfm_0_9b_d90_no_tvz_stirling_depths.xml, src/test/java/nz/cri/gns/NZSHM22/opensha/enumTreeBranches/NZSHM22_FaultModelsTest.java
All rakes should now be correct (all switched by 180 degrees)
=> Fix rake issue in fault models

src/integration/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_InversionRunner_IntegrationTest.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/AbstractInversionConfiguration.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_AbstractInversionRunner.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionConfiguration.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionRunner.java
=> [#152] exclude ruptures below minMag from inversion

src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/MFDManipulation.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/MFDManipulationTest.java
=> [#158] constant minMag for adding MFD uncertainty

src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/AbstractInversionConfiguration.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/MFDManipulation.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_AbstractInversionRunner.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionInputGenerator.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionRunner.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_SlipRateInversionConstraintBuilder.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_SubductionInversionInputGenerator.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_SubductionInversionRunner.java
closes #159 
and fixes a subduction bug introduced in #158
=> [#159] unmodifed stdev for slip rate uncertainty

src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/MFDManipulation.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionTargetMFDs.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/MFDManipulationTest.java
=> [#162] fix MFDs with 0 rates

src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_InversionFaultSystemRuptSet.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_TvzSections.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/RegionSections.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_TvzSectionsTest.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/RegionSectionsTest.java
=> [#216] fix NZSHM22_TvzSections serialisation

src/main/java/nz/cri/gns/NZSHM22/opensha/enumTreeBranches/NZSHM22_DeformationModel.java
=> [#236] fix deformation model names

src/main/java/nz/cri/gns/NZSHM22/opensha/timeDependent/MREData.java, src/main/java/nz/cri/gns/NZSHM22/opensha/timeDependent/TimeDependentRatesGenerator.java, src/main/java/nz/cri/gns/NZSHM22/opensha/util/NZSHM22_PythonGateway.java, src/main/java/nz/cri/gns/NZSHM22/opensha/util/SimpleGeoJsonBuilder.java, src/main/resources/timeDependent/ConditionalProbData_CFM1_1.csv, src/test/java/nz/cri/gns/NZSHM22/opensha/timeDependent/MREDataTest.java
closes #268 and #269 
still a WIP, needs tests
=> [#269][#269] time dependent rates generator

src/main/java/nz/cri/gns/NZSHM22/opensha/timeDependent/Aperiodicity.java, src/main/java/nz/cri/gns/NZSHM22/opensha/timeDependent/ProbabilityModelsCalc.java, src/main/java/nz/cri/gns/NZSHM22/opensha/timeDependent/TimeDependentRatesGenerator.java
=> [#273] aperiodicity options to time dependency

README.md, build.gradle
Makes merging `opensha` upstream possible as per #288 
Also updates `readme.md` to make it easier to pick up the project
=> [288] update build.gradle to allow for upstream merge of opensha

src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_AbstractInversionRunner.java
Resolves #296 
We want to be able to run an inversion with the perturbation function `VARIABLE_EXPONENTIAL_SCALE ` which requires the `variablePerturbationBasis` to be set on the `SimulatedAnnealing`.
This change allows for using an existing rates files or calculating a default based on UCERF3 code as found by Chris Rollins.
=> [296] add variablePerturbationBasis

src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/experimental/ThinningCrustal.java, src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/experimental/ThinningSubduction.java
Uses the filters from the experimental rupture thinning report to actually filter a rupture set.
=> Apply rupture thinning filters to rupture sets

src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/experimental/RuptureAccumulator.java
Preserve average slip when combining rupture sets into one.
=> RuptureAccumulator: preserve slip

src/main/java/nz/cri/gns/NZSHM22/opensha/ruptures/NZSHM22_AbstractRuptureSetBuilder.java
Satisfies #340 
Tried it out. Works.
=> [340] Setter for downDipFile in RuptureSetBuilder

changelog.md, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_AbstractInversionRunner.java
=> [352] Tidy up inversion

doc/inversion-cookbook.md, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_AbstractInversionRunner.java
fixes #360 
Ensures that inversion terminates by not using a compound completion criteria as the sub completion criteria.
=> [360] Fix inversion completion termination

src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/LoggingCompletionCriteria.java, src/main/java/nz/cri/gns/NZSHM22/util/DataLogger.java, src/test/java/nz/cri/gns/NZSHM22/opensha/inversion/LoggingCompletionCriteriaTest.java, src/test/java/nz/cri/gns/NZSHM22/util/DataLoggerTest.java
Most of this is moving code from one class to another. The only actual changes are the two new `dump` methods.
=> [366] add matrix logging capability

.github/workflows/gradle.yml
🙃 
Compare this to line 24 which is the condition for checking out our special opensha branch for regular PRs
=> [373] fix scheduled build

.github/workflows/gradle.yml, .gitignore
=> [365] Codecov

doc/investigations/potentially-unused-features.md
=> [382] investigation: unused features

doc/polygoniser.md, src/main/java/nz/cri/gns/NZSHM22/opensha/polygonise/NZSHM22_PolygonisedDistributedModelBuilder.java, src/main/java/nz/cri/gns/NZSHM22/opensha/util/ParameterRunner.java, src/main/java/nz/cri/gns/NZSHM22/util/ZipTools.java
=> [385] polygoniser investigation

.gitignore, README.md, jupyterLog/Dockerfile, jupyterLog/README.md, src/main/java/nz/cri/gns/NZSHM22/opensha/enumTreeBranches/NZSHM22_PaleoRates.java, src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_CrustalInversionTargetMFDs.java, src/main/java/nz/cri/gns/NZSHM22/opensha/util/JupyterLogger.java, src/main/java/nz/cri/gns/NZSHM22/opensha/util/JupyterNotebook.java, src/main/java/nz/cri/gns/NZSHM22/opensha/util/NZSHM22_PythonGateway.java, src/main/java/nz/cri/gns/NZSHM22/opensha/util/ParameterRunner.java, src/test/java/nz/cri/gns/NZSHM22/opensha/util/JupyterNotebookTest.java
closes #380
I haven't written tests for JupyterLogger yet because I expect this to change in the next few months or even weeks as we find out how we actually use it.
=> [380] log debug data to Jupyter
